backend:
  name: github
  repo: henryandpartners/living-archive-web
  branch: main
  base_url: https://living-archive-web.vercel.app
  auth_endpoint: api/auth

publish_mode: editorial_workflow
media_folder: "public/uploads"
public_folder: "/uploads"
site_url: https://living-archive-web.vercel.app
display_url: https://living-archive-web.vercel.app
logo_url: https://living-archive-web.vercel.app/favicon.ico

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Page Title", name: "title", widget: "string" }

  - name: "chapters"
    label: "Chapters"
    label_singular: "Chapter"
    folder: "content/chapters"
    create: false
    extension: "md"
    slug: "{{fields.number}}"
    fields:
      - { label: "Chapter Number", name: "number", widget: "number", value_type: "int", min: 1, max: 9 }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Short Label (TOC)", name: "short", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "YouTube URL", name: "video_url", widget: "string", required: false }
